name: Install Dependencies

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  install_dependencies:
    runs-on: ubuntu-latest  # You can change the OS if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Adjust the Python version as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Display installed packages
      run: |
        pip list
